### ISSUE TITLE
Documentation leads to nowhere

### ISSUE THREAD

**Issue by Remyapraveen** [RoadieHQ/backstage-auth-example#54]
Hi, I am trying to integrate the Auth0 into my backstage instance and was following the instructions from the repo here. But the link at the end of the instructions leads to nowhere. Could you please fix it : " https://backstage.io/docs/tutorials/quickstart-app-auth"

![image](https://user-images.githubusercontent.com/93478132/225570489-77b86b01-3a7e-4206-aaef-1e7b8724297a.png)

**Comment by Xantier** [comment]
Updated
